model:
  input_dim: 150
  hidden_dim: 64
  layer_dim: 2
  output_dim: 4

training:
  batch_size: 8
  learning_rate: 0.0003
  num_epochs: 50

data:
  train_split: 0.8
  data_path: "./data/ecommerceDataset.csv"

paths:
  result_dir: "./train_results/"
